### PR TITLE
Feat/implement UI migration

### PR DESCRIPTION
**Pull request by khayss**
## Summary by CodeRabbit

- **New Features**
  - Enhanced proposal creation process in the Lender component.
  - Added interactive input handling for interest rates using a range slider.
  - Improved user data management related to loan creation.

- **Bug Fixes**
  - Updated input handling to ensure data integrity when creating proposals.

- **Style**
  - Minor formatting improvements for better readability in the UI components.

### CODE REVIEW

**Review by Peerprotocol — COMMENTED** [review]
hey chief, please can we remove these auto generated files from the commit as suggested by the code review?

**Comment by khayss** [comment]
Yeah, will make the update asap.

**Comment by khayss** [comment]
> hey chief, please can we remove these auto generated files from the commit as suggested by the code review?

Done

**Comment by Peerprotocol** [comment]
hey @khayss there are some conflicts in the above mentioned file, please can you help resolve them?

update your fork with the main branch and help resolve these conflicts

**Comment by khayss** [comment]
Resolved the conflicts

**Review by Dprof-in-tech — APPROVED** [review]
approved.

**Pull request merged**
